# Generated by Django 3.1.1 on 2020-10-25 06:36

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='pub_date',
            field=models.DateField(default=datetime.datetime(2020, 10, 25, 12, 6, 7, 770440)),
        ),
    ]
